Better support for long-option --help

diff --git a/ucpp/ucpp-init b/ucpp/ucpp-init
--- a/ucpp/ucpp-init
+++ b/ucpp/ucpp-init
@@ -14,7 +14,7 @@ EOF
 
 source ucpp_settings
 
-while getopts "ht:" opt; do
+while getopts "ht:-:" opt; do
 	case $opt in
 		h)
 			usage
@@ -29,6 +29,20 @@ while getopts "ht:" opt; do
 				echo "Invalid team number"
 				exit 1
 			fi
+			;;
+		-)
+			case $OPTARG in
+				help)
+					usage
+					exit
+					;;
+				*)
+					echo "Invalid option: --$OPTARG" >&2
+					usage >&2
+					exit 1
+					;;
+			esac
+			echo "Invalid option: --$OPTARG" >&2
 			;;
 		\?)
 			echo "Invalid option: -$OPTARG" >&2
diff --git a/ucpp/ucpp-setup b/ucpp/ucpp-setup
--- a/ucpp/ucpp-setup
+++ b/ucpp/ucpp-setup
@@ -34,7 +34,7 @@ EOF
 	fi
 	cat <<EOF
 Options
-  -h, --help, help
+  -h, --help
       Display this help and exit
   -t <team-number>
       Set default team number for deploying code
@@ -90,13 +90,13 @@ then
 	shift
 fi
 
-if [ "x$1" = "xhelp" ] || [ "x$1" = "x--help" ] || [ "x$platform" = "x" ]
+if [ "x$platform" = "x" ]
 then
 	usage
 	exit
 fi
 
-while getopts "ht:c:" opt; do
+while getopts "ht:c:-:" opt; do
 	case $opt in
 		h)
 			usage
@@ -114,6 +114,19 @@ while getopts "ht:c:" opt; do
 			;;
 		c)
 			C_DRIVE=$OPTARG
+			;;
+		-)
+			case $OPTARG in
+				help)
+					usage
+					exit
+					;;
+				*)
+					echo "Invalid option: --$OPTARG" >&2
+					usage >&2
+					exit 1
+					;;
+			esac
 			;;
 		\?)
 			echo "Invalid option: -$OPTARG" >&2
