Cleanup

diff --git a/ucpp/ucpp-configure b/ucpp/ucpp-configure
--- a/ucpp/ucpp-configure
+++ b/ucpp/ucpp-configure
@@ -1,5 +1,11 @@
 #! /bin/bash
 
+die()
+{
+	echo "$1"
+	exit 1
+}
+
 usage()
 {
 	cat <<EOF
@@ -66,11 +72,10 @@ case "x$HAVE_CPP_PROJECT" in
 	xno)
 		echo "Current directory is not configured as a C++ project"
 		echo "Run ucpp init -t <team-number>"
-		exit 66
+		exit 1
 		;;
 	x)
-		echo "ERROR: failed to load settings"
-		exit 66
+		die "ERROR: failed to load settings"
 		;;
 esac
 
@@ -220,7 +225,7 @@ then
 	else
 		echo "WindRiver Makefile not found"
 		echo "Generate the Makefile or use other configuration methods"
-		exit 66
+		exit 1
 	fi
 fi
 
diff --git a/ucpp/ucpp-init b/ucpp/ucpp-init
--- a/ucpp/ucpp-init
+++ b/ucpp/ucpp-init
@@ -1,5 +1,11 @@
 #! /bin/bash
 
+die()
+{
+	echo "$1"
+	exit 1
+}
+
 usage()
 {
 	cat <<EOF
@@ -26,8 +32,7 @@ while getopts "ht:-:" opt; do
 			DEPLOY_IP="10.${HUNDREDS}.${UNDER_HUNDREDS}.2"
 			if [ "x$DEPLOY_IP" = "x10...2" ]
 			then
-				echo "Invalid team number"
-				exit 1
+				die "Invalid team number"
 			fi
 			;;
 		-)
@@ -42,7 +47,6 @@ while getopts "ht:-:" opt; do
 					exit 1
 					;;
 			esac
-			echo "Invalid option: --$OPTARG" >&2
 			;;
 		\?)
 			echo "Invalid option: -$OPTARG" >&2
@@ -153,7 +157,7 @@ EOF
 mkdir -p PPC603gnu
 
 # On Windows, don't use the Linux Makefile
-case `uname` in 
+case `uname` in
 	windows32|MINGW*)
 		mv Makefile PPC603gnu/Makefile_tmp
 		cat PPC603gnu/Makefile_tmp | sed -e "s/Makefile_linux/Makefile/g" > Makefile
diff --git a/ucpp/ucpp-setup b/ucpp/ucpp-setup
--- a/ucpp/ucpp-setup
+++ b/ucpp/ucpp-setup
@@ -1,19 +1,10 @@
 #! /bin/bash
 
-case `uname` in 
-	Linux*)
-		platform=linux-gccdist
-		C_DRIVE=$HOME/.ucpp/gccdist/
-		;;
-	windows32|MINGW*)
-		platform=windows-git
-		C_DRIVE=/c/
-		;;
-	CYGWIN*)
-		platform=windows-cygwin
-		C_DRIVE=/cygdrive/c/
-		;;
-esac
+die()
+{
+	echo "$1"
+	exit 1
+}
 
 usage()
 {
@@ -32,6 +23,7 @@ Usage: ucpp setup [PLATFORM] [-t <team-number>]
 
 EOF
 	fi
+
 	cat <<EOF
 Options
   -h, --help
@@ -43,7 +35,7 @@ Options
         Set the path equivalent to the C:/ drive
         (the parent directory of the WindRiver folder)
         NOTE: requires trailing slash (/)
-      
+
 Available Platforms:
   linux-gccdist
       Set up Linux system that automatically downloads
@@ -63,6 +55,21 @@ Available Platforms:
 EOF
 }
 
+case `uname` in 
+	Linux*)
+		platform=linux-gccdist
+		C_DRIVE=$HOME/.ucpp/gccdist/
+		;;
+	windows32|MINGW*)
+		platform=windows-git
+		C_DRIVE=/c/
+		;;
+	CYGWIN*)
+		platform=windows-cygwin
+		C_DRIVE=/cygdrive/c/
+		;;
+esac
+
 if [ "x$1" = "xlinux-windriver" ]
 then
 	platform=linux-windriver
@@ -81,6 +88,7 @@ if [ "x$1" = "xwindows-cygwin" ]
 then
 	platform=windows-cygwin
 	C_DRIVE=/cygdrive/c/
+	shift
 fi
 
 if [ "x$1" = "xwindows-git" ]
@@ -92,8 +100,8 @@ fi
 
 if [ "x$platform" = "x" ]
 then
-	usage
-	exit
+	usage >&2
+	exit 1
 fi
 
 while getopts "ht:c:-:" opt; do
@@ -108,8 +116,7 @@ while getopts "ht:c:-:" opt; do
 			DEPLOY_IP="10.${HUNDREDS}.${UNDER_HUNDREDS}.2"
 			if [ "x$DEPLOY_IP" = "x10...2" ]
 			then
-				echo "Invalid team number"
-				exit 1
+				die "Invalid team number"
 			fi
 			;;
 		c)
