Update WPILib downloader for 2012 initial WPILib release

diff --git a/ucpp/ucpp-setup b/ucpp/ucpp-setup
--- a/ucpp/ucpp-setup
+++ b/ucpp/ucpp-setup
@@ -224,9 +224,9 @@ function install_wpilib()
 	[ -d gccdist ] || die "Cannot install WPILib: gccdist not found"
 
 	echo -n "-----> Checking for WPILib updates... "
-	wget -q http://firstforge.wpi.edu/sf/frs/do/viewSummary/projects.wpilib/frs -O - | grep 'WPILib C++ update' | sed "s/.*<a href=\"\([^\"]*\)\">.*/http:\/\/firstforge.wpi.edu\1/" | uniq | sed "s/;.*//" > wpilib_page1.url
+	wget -q http://firstforge.wpi.edu/sf/frs/do/viewSummary/projects.wpilib/frs -O - | grep '2012 C++ Update for FRC' | sed "s/.*<a href=\"\([^\"]*\)\">.*/http:\/\/firstforge.wpi.edu\1/" | uniq | sed "s/;.*//" > wpilib_page1.url
 	wget `cat wpilib_page1.url` -q -O - | grep "rel[0-9][0-9]*" | grep href | sed "s/.*\(rel[0-9]*\)/\1/" | sort -r | head -n 1 | sed "s/.*<a href=\"\([^\"]*\).*/http:\/\/firstforge.wpi.edu\1/" | sed "s/;.*//" > wpilib_page2.url
-	wget `cat wpilib_page2.url` -q -O - | grep "\.exe\s*<\/a>" | sed "s/.*<a href=\"\([^\"]*\)\".*/http:\/\/firstforge.wpi.edu\1/" | sed "s/;.*//" > wpilib_page3.url
+	wget `cat wpilib_page2.url` -q -O - | grep "\.zip\s*<\/a>" | sed "s/.*<a href=\"\([^\"]*\)\".*/http:\/\/firstforge.wpi.edu\1/" | sed "s/;.*//" > wpilib_page3.url
 
 	touch wpilib_last_downloaded.url
 	if [ "x`cat wpilib_page3.url`" == "x`cat wpilib_last_downloaded.url`" ]; then
@@ -234,7 +234,13 @@ function install_wpilib()
 	else
 		echo "updates available"
 		echo "-----> WPILib download ..."
-		wget `cat wpilib_page3.url` -O wpilibupdate.exe
+		wget `cat wpilib_page3.url` -O wpilibupdate.zip
+		echo "You will need to enter this year's password"
+		unzip wpilibupdate.zip || {
+			echo "Unzip failed, perhaps you entered the wrong password"
+			exit 1
+		}
+		mv WorkbenchUpdate*.exe wpilibupdate.exe
 		mv wpilib_page3.url wpilib_last_downloaded.url
 		echo "-----> WPILib download [DONE]"
 	fi
